export const books = [
  // Self-Improvement
  {
    id: 1,
    slug: "atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self-Improvement",
    rating: 4.5,
    available: 8,
    coverColor: "bg-green-600",
    description:
      "Cara Efektif Bagi Dirimu untuk Mengubah Hidup Anda Menjadi Lebih Baik",
    tags: ["Self Help", "Productivity", "Psychology"],
  },
  {
    id: 2,
    slug: "think-and-grow-rich",
    title: "Think And Grow Rich",
    author: "Napoleon Hill",
    category: "Self-Improvement",
    rating: 4.3,
    available: 12,
    coverColor: "bg-yellow-500",
    description:
      "Meraih Impian, Kesuksesan, dan Kekayaan Mutlak Melalui Kekuatan Pikiran",
    tags: ["Success", "Wealth", "Mindset"],
  },
  {
    id: 3,
    slug: "psychology-of-emotion",
    title: "The Psychology Of Emotion",
    author: "David J. Lieberman",
    category: "Self-Improvement",
    rating: 4.2,
    available: 5,
    coverColor: "bg-blue-600",
    description: "Understanding human emotions and behavioral patterns",
    tags: ["Psychology", "Emotions", "Behavior"],
  },
  {
    id: 4,
    slug: "intelligent-investor",
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    category: "Self-Improvement",
    rating: 4.7,
    available: 6,
    coverColor: "bg-blue-800",
    description: "Buku Karya Investor Terhebat Benjamin Graham",
    tags: ["Investment", "Finance", "Strategy"],
  },
  {
    id: 5,
    slug: "psychology-of-money",
    title: "The Psychology Of Money",
    author: "Morgan Housel",
    category: "Self-Improvement",
    rating: 4.6,
    available: 9,
    coverColor: "bg-green-700",
    description: "Understanding wealth, greed, and happiness",
    tags: ["Finance", "Psychology", "Wealth"],
  },
  {
    id: 6,
    slug: "principles-of-power",
    title: "The Principles Of Power",
    author: "Dion Yulianto",
    category: "Self-Improvement",
    rating: 4.1,
    available: 7,
    coverColor: "bg-gray-800",
    description: "Mastering influence and leadership principles",
    tags: ["Leadership", "Power", "Strategy"],
  },
  {
    id: 7,
    slug: "art-of-money",
    title: "The Art Of Money",
    author: "Indra Ramawan",
    category: "Self-Improvement",
    rating: 4.4,
    available: 11,
    coverColor: "bg-green-600",
    description: "Strategi mengatur keuangan dengan bijak",
    tags: ["Finance", "Money Management", "Investment"],
  },
  {
    id: 8,
    slug: "rich-dad-poor-dad",
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    category: "Self-Improvement",
    rating: 4.8,
    available: 15,
    coverColor: "bg-blue-700",
    description: "What the rich teach their kids about money",
    tags: ["Finance", "Education", "Wealth"],
  },
  {
    id: 9,
    slug: "warren-buffett",
    title: "Warren Buffett",
    author: "A. Yogeswara",
    category: "Biography",
    rating: 4.3,
    available: 4,
    coverColor: "bg-gray-700",
    description: "Biography of the legendary investor",
    tags: ["Biography", "Investment", "Success"],
  },
  {
    id: 10,
    slug: "power-of-sun-tzu",
    title: "The Power Of Sun Tzu",
    author: "Sun Tzu",
    category: "Self-Improvement",
    rating: 4.5,
    available: 10,
    coverColor: "bg-green-800",
    description: "Ancient wisdom for modern strategy",
    tags: ["Strategy", "Philosophy", "Leadership"],
  },

  // Politics-Biography
  {
    id: 11,
    slug: "origins-of-political-order",
    title: "The Origins of Political Order",
    author: "Francis Fukuyama",
    category: "Politics-Biography",
    rating: 4.4,
    available: 3,
    coverColor: "bg-red-800",
    description: "From Prehuman Times to the French Revolution",
    tags: ["Politics", "History", "Society"],
  },
  {
    id: 12,
    slug: "naar-de-republik-indonesia",
    title: 'Naar De "Republik Indonesia"',
    author: "Tan Malaka",
    category: "Politics-Biography",
    rating: 4.6,
    available: 2,
    coverColor: "bg-red-700",
    description: "Karya monumental tentang perjuangan kemerdekaan",
    tags: ["Politics", "Biography", "History"],
  },
  {
    id: 13,
    slug: "madilog",
    title: "Madilog",
    author: "Tan Malaka",
    category: "Politics-Biography",
    rating: 4.7,
    available: 4,
    coverColor: "bg-red-600",
    description: "Materialisme, Dialektika, dan Logika",
    tags: ["Philosophy", "Politics", "Logic"],
  },
  {
    id: 14,
    slug: "aksi-massa",
    title: "Aksi Massa",
    author: "Tan Malaka",
    category: "Politics-Biography",
    rating: 4.5,
    available: 3,
    coverColor: "bg-red-700",
    description: "Strategi perjuangan dan aksi massa",
    tags: ["Politics", "History", "Revolution"],
  },
  {
    id: 15,
    slug: "dari-penjara-ke-penjara",
    title: "Dari Penjara Ke Penjara",
    author: "Tan Malaka",
    category: "Politics-Biography",
    rating: 4.8,
    available: 5,
    coverColor: "bg-gray-900",
    description: "Memoar perjuangan seorang revolusioner",
    tags: ["Biography", "Politics", "Memoir"],
  },
  {
    id: 16,
    slug: "48-laws-of-power",
    title: "48 Laws Of Power",
    author: "Robert Greene",
    category: "Politics",
    rating: 4.5,
    available: 10,
    coverColor: "bg-red-800",
    description: "The essential guide to power and strategy",
    tags: ["Strategy", "Power", "Leadership"],
  },
  {
    id: 17,
    slug: "communist-manifesto",
    title: "The Communist Manifesto",
    author: "Karl Marx, Frederick Engels",
    category: "Politics",
    rating: 4.2,
    available: 6,
    coverColor: "bg-red-600",
    description: "Classic political philosophy text",
    tags: ["Politics", "Philosophy", "Economics"],
  },

  // Fiction
  {
    id: 18,
    slug: "transformers-exiles",
    title: "Transformers: Exiles",
    author: "Alex Irvine",
    category: "Fiction",
    rating: 4.0,
    available: 7,
    coverColor: "bg-gray-900",
    description: "Epic science fiction adventure",
    tags: ["Sci-Fi", "Adventure", "Action"],
  },
  {
    id: 19,
    slug: "star-wars-last-command",
    title: "Star Wars: The Last Command",
    author: "Timothy Zahn",
    category: "Fiction",
    rating: 4.6,
    available: 8,
    coverColor: "bg-gray-800",
    description: "Thrawn Trilogy Book 3",
    tags: ["Sci-Fi", "Star Wars", "Adventure"],
  },
  {
    id: 20,
    slug: "star-wars-light-of-jedi",
    title: "Star Wars: Light Of The Jedi",
    author: "Charles Soule",
    category: "Fiction",
    rating: 4.4,
    available: 9,
    coverColor: "bg-yellow-700",
    description: "The High Republic era begins",
    tags: ["Sci-Fi", "Star Wars", "Fantasy"],
  },
  {
    id: 21,
    slug: "star-wars-lords-of-sith",
    title: "Star Wars: Lords Of The Sith",
    author: "Paul S Kemp",
    category: "Fiction",
    rating: 4.3,
    available: 6,
    coverColor: "bg-red-900",
    description: "Vader and the Emperor's dark alliance",
    tags: ["Sci-Fi", "Star Wars", "Dark Side"],
  },

  // Novel
  {
    id: 22,
    slug: "angels-and-demons",
    title: "Angels & Demons",
    author: "Dan Brown",
    category: "Novel",
    rating: 4.5,
    available: 12,
    coverColor: "bg-gray-900",
    description: "Thriller mystery by Dan Brown",
    tags: ["Mystery", "Thriller", "Adventure"],
  },
  {
    id: 23,
    slug: "frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    category: "Novel",
    rating: 4.3,
    available: 10,
    coverColor: "bg-gray-800",
    description: "Classic gothic horror novel",
    tags: ["Horror", "Classic", "Gothic"],
  },
  {
    id: 24,
    slug: "wuthering-heights",
    title: "Wuthering Heights",
    author: "Emily Bronte",
    category: "Novel",
    rating: 4.2,
    available: 8,
    coverColor: "bg-gray-700",
    description: "Classic romantic tragedy",
    tags: ["Romance", "Classic", "Drama"],
  },
  {
    id: 25,
    slug: "da-vinci-code",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    category: "Novel",
    rating: 4.6,
    available: 14,
    coverColor: "bg-red-800",
    description: "International bestselling mystery thriller",
    tags: ["Mystery", "Thriller", "Conspiracy"],
  },
  {
    id: 26,
    slug: "art-of-war",
    title: "Art Of War",
    author: "Sun Tzu",
    category: "Novel",
    rating: 4.7,
    available: 15,
    coverColor: "bg-red-700",
    description: "Ancient military treatise",
    tags: ["Strategy", "Philosophy", "Classic"],
  },
  {
    id: 27,
    slug: "sejarah-dunia-yang-disembunyikan",
    title: "Sejarah Dunia Yang Disembunyikan",
    author: "Jonathan Black",
    category: "Novel",
    rating: 4.1,
    available: 5,
    coverColor: "bg-yellow-900",
    description: "Uncovering hidden world history",
    tags: ["History", "Mystery", "Non-Fiction"],
  },
];

export const categories = [
  { name: "Self-Improvement", count: 10 },
  { name: "Romance", count: 8 },
  { name: "Fiction", count: 15 },
  { name: "Non-Fiction", count: 12 },
  { name: "Politics", count: 7 },
  { name: "Finance & Economics", count: 9 },
  { name: "Biography", count: 6 },
];

export const recentlyAdded = [
  books.find((b) => b.slug === "48-laws-of-power"),
  books.find((b) => b.slug === "dari-penjara-ke-penjara"),
  books.find((b) => b.slug === "rich-dad-poor-dad"),
];

export const forYou = [
  books.find((b) => b.slug === "origins-of-political-order"),
  books.find((b) => b.slug === "principles-of-power"),
  books.find((b) => b.slug === "naar-de-republik-indonesia"),
  books.find((b) => b.slug === "warren-buffett"),
  books.find((b) => b.slug === "power-of-sun-tzu"),
  books.find((b) => b.slug === "think-and-grow-rich"),
  books.find((b) => b.slug === "atomic-habits"),
  books.find((b) => b.slug === "art-of-money"),
];
